### ISSUE TITLE
terminix-bin-1.4.2 incorrect manifest

### ISSUE THREAD

**Issue by simonvanderveldt** [Kami-no/overlay#1]
Hi @Kami-no Thanks for the terminix ebuild! I tried to use it to install 1.4.2, but it errored after downloading the zip, the checksums in the manifest aren't correct. [Seems like you copied the one from 1.3.5 to the newer ones](https://github.com/Kami-no/overlay/blob/master/x11-terms/terminix-bin/Manifest#L6), which obviously won't work :)

Don't know if you know, but if you delete the Manifest file `x11-terms/terminix-bin/Manifest`and run `repoman manifest` in the root of your overlay directory `repoman` will regenerate it with the correct checksums :)

**Comment by Kami-no** [comment]
Well, it's all with variables any way.
But you're right, there were some changes that were not updated... in distro

https://github.com/Kami-no/overlay/commit/865b374e01b1f4b8588a6b34af0f9ad08823d0cb

My script to update overlay:
```
#!/bin/bash

pushd ./
repoman manifest
popd
chown -R portage:portage /var/lib/portage/repos/kami-no
```
